services:

  redis:
    container_name: redis
    image: redis:8.4
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - app-tier
    ports:
      - 6379:6379
    volumes:
      - ./data:/data

  redis-commander:
    container_name: redis-commander
    image: ghcr.io/joeferner/redis-commander:0.9
    restart: always
    environment:
      REDIS_HOSTS: local:redis:6379:0:${REDIS_PASSWORD}
    networks:
      - app-tier
    ports:
      - 8082:8081
    depends_on:
      - redis

networks:
  app-tier:
    driver: bridge
